/**
 * Author: Ankit Jain
 * Project Name: Icicle App
 * Date: 01-March-2018
 */

/*Get authenticated profile details action*/
export const FETCH_PROFILE_DETAILS = "FETCH_PROFILE_DETAILS";
export const FETCH_PROFILE_DETAILS_SUCCEEDED = "FETCH_PROFILE_DETAILS_SUCCEEDED";
export const FETCH_PROFILE_DETAILS_FAILED = "FETCH_PROFILE_DETAILS_FAILED";

/*Update member profile picture action*/
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const UPDATE_PROFILE_PICTURE_SUCCEEDED = "UPDATE_PROFILE_PICTURE_SUCCEEDED";
export const UPDATE_PROFILE_PICTURE_FAILED = "UPDATE_PROFILE_PICTURE_FAILED";